
export type EmotionalState = 'engaged' | 'frustrated' | 'bored' | 'breakthrough';

// Educational facts about music - shown occasionally to keep practice engaging
const MUSIC_FACTS = {
    bossaNova: [
        "Bossa Nova was born in Rio de Janeiro in the late 1950s, blending samba rhythms with cool jazz harmonies.",
        "João Gilberto is considered the father of Bossa Nova. His quiet, intimate singing style revolutionized Brazilian music.",
        "The name 'Bossa Nova' roughly translates to 'new trend' or 'new wave' in Portuguese.",
        "'The Girl from Ipanema' is the second most recorded song in history, after 'Yesterday' by The Beatles.",
        "Tom Jobim studied with German-Brazilian composer Hans-Joachim Koellreutter, who introduced him to impressionist harmony.",
        "The iconic Bossa Nova rhythm pattern was inspired by João Gilberto playing a samba groove on a single guitar.",
        "Stan Getz's 1964 album 'Getz/Gilberto' brought Bossa Nova to worldwide audiences and won Album of the Year.",
        "Nara Leão was known as 'the muse of Bossa Nova' and her apartment was a gathering place for the movement's founders.",
        "Baden Powell merged Bossa Nova with Afro-Brazilian rhythms, creating the 'Afro-Samba' style.",
        "The chord progression ii-V-I is the backbone of both jazz and Bossa Nova harmony.",
        "Roberto Menescal's 'O Barquinho' was written after his boat engine failed at sea.",
        "Newton Mendonça was Tom Jobim's frequent lyricist partner, co-writing 'Desafinado' and 'Samba de Uma Nota Só'.",
        "Bossa Nova lyrics often focus on themes of nature, love, and the beach culture of Rio in the 50s.",
        "Ronaldo Bôscoli was a key journalist and lyricist who helped define the Bossa Nova aesthetic.",
        "The movement started in the Zona Sul (South Zone) of Rio, primarily in Copacabana and Ipanema.",
        "Vinicius de Moraes, a diplomat and poet, wrote the lyrics for many Bossa Nova classics including 'Chega de Saudade'.",
        "Elis Regina, though famously critical of Bossa Nova's 'coolness', recorded arguably the definitive version of 'Águas de Março'.",
        "João Donato added a funky, syncopated piano style that influenced later Bossa Nova and Jazz Fusion.",
        "Sergio Mendes helped popularize Bossa Nova in the US with his group Brasil '66.",
        "Bossa Nova drumming typically involves a rim click pattern on the snare mimicking the tamborim.",
        "The guitar rhythm usually stresses the '2' and the 'and of 3' or '4' in a 4/4 bar.",
        "Luiz Bonfá compsed 'Manhã de Carnaval' for the film 'Black Orpheus', becoming an international jazz standard.",
        "The decline of Bossa Nova coincided with the rise of the politically charged MPB (Música Popular Brasileira) genre.",
        "Sylvia Telles was one of the first professional singers to dedicate her repertoire to Bossa Nova.",
        "Durval Ferreira was a key guitarist and composer who helped bridge Bossa Nova with Sambajazz.",
        "Sambajazz is an instrumental offshoot of Bossa Nova that focuses on high energy and improvisation.",
        "Leny Andrade is nicknamed the 'First Lady of Sambajazz' for her vocal improvisational skills.",
        "Cartola, a samba legend, wasn't Bossa Nova but his harmonic sophistication heavily influenced the genre.",
        "Johnny Alf is often cited as a precursor to Bossa Nova, playing modern harmonies in Rio nightclubs in the early 50s.",
        "Bossa Nova's whisper-singing style was partly a necessity due to poor microphone quality in small clubs.",
        "Oscar Castro-Neves was a central figure in bringing Bossa Nova to Carnegie Hall in 1962.",
        "The 1962 Carnegie Hall concert was chaotic but pivotal in cementing Bossa Nova's status in the US.",
        "Toquinho was Vinicius de Moraes's final major musical partner, bridging Bossa with pop.",
        "Wanda Sá is one of the few female guitarists/singers from the original Bossa Nova era still active.",
        "Marcos Valle started in Bossa Nova but evolved into funk, soul, and disco genres.",
        "Carlos Lyra was known for his more political lyrics and melodic sweetness.",
        "Zimbo Trio is a famous instrumental trio representing the Sambajazz style.",
        "Tamba Trio popularized the 'samba drive' rhythmic feel.",
        "Agostinho dos Santos sang 'Manhã de Carnaval' on the 'Black Orpheus' soundtrack.",
        "Alaíde Costa is known for her unique, whispery vocal timbre and sophisticated phrasing.",
        "Bossa Nova harmony often uses 'slash chords' (e.g., C/Bb) to create tension and movement.",
        "The 11th leads to the 3rd and the 13th leads to the 7th in many dominant voicings.",
        "Bossa rhythms are 2/4 in Samba tradition but often notated as 4/4 in Jazz Real Books.",
        "Claus Ogerman's lush orchestral arrangements became synonymous with Jobim's sound.",
        "Eumir Deodato arranged for Sinatra and Jobim before becoming a funk-jazz star.",
        "Airto Moreira, a percussionist, brought Brazilian rhythms to Miles Davis and Weather Report.",
        "Flora Purim is a jazz fusion singer known for her 6-octave range and work with Chick Corea.",
        "Hermeto Pascoal is known as 'O Bruxo' (The Wizard) for his genius and unconventional instrumentation.",
        "Egberto Gismonti blends Bossa, classical, and indigenous Brazilian music on guitar and piano.",
        "Bossa Nova implies a 'flat' singing style with little vibrato, contrasting with the operatic style of the 50s.",
        "The 'batida' is the specific rhythmic pattern played on the guitar in Bossa Nova.",
        "Bossa Nova was initially criticized by some Brazilian traditionalists as being 'out of tune' (desafinado).",
        "The film 'Black Orpheus' (1959) was crucial in introducing Bossa Nova to an international audience.",
        "Astrud Gilberto, João's wife, wasn't a professional singer when she recorded 'The Girl from Ipanema'.",
        "Bossa Nova compositions often feature long, chromatic melodic lines.",
        "The genre was heavily influenced by French Impressionist composers like Debussy and Ravel.",
        "Bossa Nova is often described as 'samba played with jazz chords'.",
        "The 'Bossa Nova' beat is softer and more relaxed than traditional Samba.",
        "Many Bossa Nova songs have complex structures, avoiding standard AABA forms.",
        "The lyrics of Bossa Nova marked a shift from the tragic themes of Samba-Canção to more optimistic topics.",
        "Bossa Nova's popularity in the US led to a jazz-bossa fusion craze in the 1960s.",
        "Frank Sinatra recorded two albums with Antonio Carlos Jobim, cementing the genre's status.",
        "The 'Bossa Nova' rhythm is often played on the hi-hat in jazz drumming.",
        "Bossa Nova guitarists often use nylon-string guitars for a warmer, mellower tone.",
        "The 'Bossa Nova' style influenced many pop and rock musicians, including The Beatles and The Beach Boys.",
        "Bossa Nova is considered one of Brazil's most significant cultural exports.",
        "The genre's sophisticated harmonies require a high level of musical proficiency.",
        "Bossa Nova's influence can be heard in modern genres like Acid Jazz and Drum and Bass.",
        "The 'Bossa Nova' movement was short-lived in Brazil but had a lasting global impact.",
        "Many Bossa Nova standards are now part of the core jazz repertoire.",
        "The 'Bossa Nova' style is characterized by its 'cool' and understated aesthetic.",
        "Bossa Nova singers often phrase behind the beat, creating a relaxed feel.",
        "The genre's harmonic language includes frequent use of altered dominants and diminished chords.",
        "Bossa Nova's rhythmic feel is often described as 'swaying' rather than 'swinging'.",
        "The 'Bossa Nova' craze in the US peaked in the mid-1960s.",
        "Many Bossa Nova musicians fled Brazil during the military dictatorship in the 1960s and 70s.",
        "Bossa Nova remains a symbol of the 'Golden Years' of Rio de Janeiro.",
        "The genre's legacy continues to influence new generations of Brazilian musicians.",
        "Bossa Nova is often associated with the 'beach lifestyle' of Ipanema and Copacabana.",
        "The 'Bossa Nova' sound is instantly recognizable by its distinctive rhythm and harmony.",
        "Bossa Nova's integration of melody, harmony, and rhythm is considered a high point in 20th-century music.",
        "The genre's emphasis on the guitar as a harmonic and rhythmic instrument revolutionized Brazilian music.",
        "Bossa Nova's 'less is more' approach to arrangement and performance set it apart from earlier styles.",
        "The 'Bossa Nova' beat is a staple of elevator and lounge music, often leading to its dismissal as 'easy listening'.",
        "Despite its commercialization, Bossa Nova remains a complex and artistic musical form.",
        "The genre's influence extends to film scores, advertising, and background music worldwide.",
        "Bossa Nova is a testament to the power of cross-cultural musical exchange.",
        "The 'Bossa Nova' style is a perfect blend of African rhythm and European harmony.",
        "Bossa Nova's enduring popularity proves its timeless appeal.",
        "The genre's history is a fascinating story of creativity, collaboration, and cultural diplomacy."
    ],
    jazz: [
        "Bebop emerged in the 1940s as a reaction to the big band 'swing' era, featuring faster tempos and complex harmonies.",
        "The tritone substitution replaces a dominant chord with one a tritone away - V7 becomes ♭II7.",
        "Miles Davis's 'Kind of Blue' is the best-selling jazz album of all time, pioneering modal jazz.",
        "Charlie Parker could play in all 12 keys fluently, a skill that set him apart from other musicians of his era.",
        "The 'Real Book' was originally an illegal bootleg collection of jazz standards, now legitimized by Hal Leonard.",
        "Bill Evans revolutionized jazz piano voicings, often placing the 3rd and 7th in his left hand.",
        "Coltrane changes (from 'Giant Steps') divide the octave into three equal parts using major third intervals.",
        "The ii-V-I progression makes up about 80% of jazz harmony.",
        "Wes Montgomery popularized playing octaves on guitar, creating his signature thick, warm sound.",
        "Django Reinhardt played guitar with only two fingers on his fretting hand after a fire injury.",
        "Louis Armstrong is credited with inventing scat singing when he dropped his lyric sheet during a recording.",
        "Duke Ellington wrote over 1,000 compositions and led his orchestra for 50 years.",
        "Thelonious Monk's percussive style and use of silence were initially criticized before being recognized as genius.",
        "Ella Fitzgerald had a vocal range of three octaves and is known as the 'First Lady of Song'.",
        "Dave Brubeck's 'Take Five' is the biggest selling jazz single, famous for its 5/4 time signature.",
        "Ornette Coleman's 1960 album 'Free Jazz' gave its name to the avant-garde movement.",
        "Herbie Hancock was a child prodigy who played Mozart with the Chicago Symphony at age 11.",
        "Jaco Pastorius removed the frets from his bass to achieve a singing, horn-like tone.",
        "Keith Jarrett's 'The Köln Concert' is the best-selling solo piano album in jazz history.",
        "Art Blakey's Jazz Messengers was a 'finishing school' for young jazz talent like Wayne Shorter and Wynton Marsalis.",
        "Count Basie's rhythm section was known as 'The All-American Rhythm Section' for its impeccable swing.",
        "Benny Goodman led the first racially integrated jazz group to play Carnegie Hall in 1938.",
        "Billie Holiday's 'Strange Fruit' was a protest song against lynchings and a landmark in civil rights.",
        "Fats Waller was kidnapped by Al Capone's gang to play at the mobster's birthday party.",
        "Sonny Rollins took a 3-year sabbatical at the peak of his career to practice on the Williamsburg Bridge.",
        "Chet Baker was known as the 'Prince of Cool' for his trumpet playing and vocals.",
        "Stan Kenton's big band was known as the 'Wall of Sound' before Phil Spector used the term.",
        "Rahsaan Roland Kirk could play three saxophones simultaneously.",
        "Sun Ra claimed to be from Saturn and led the 'Arkestra' in futuristic costumes.",
        "Pat Metheny has won 20 Grammy Awards in 10 different categories.",
        "Chick Corea played in Miles Davis's electric band before forming Return to Forever.",
        "Weather Report was the definitive jazz fusion band of the 70s, featuring Wayne Shorter and Joe Zawinul.",
        "Cannonball Adderley's 'Mercy, Mercy, Mercy' was a crossover pop hit.",
        "Horace Silver is considered a father of 'Hard Bop', blending bebop with R&B and gospel.",
        "Max Roach was a pioneer of bebop drumming, shifting the beat from the bass drum to the ride cymbal.",
        "Charles Mingus was a virtuoso bassist known for his volatility and political activism.",
        "Lester Young was known as 'Pres' (The President) and influenced the Cool Jazz style.",
        "Dexter Gordon was the first major bebop tenor saxophonist.",
        "Bud Powell translated Charlie Parker's language to the piano, creating the modern jazz piano style.",
        "Clifford Brown died at 25 in a car accident, cutting short one of the most promising careers in jazz.",
        "Sarah Vaughan was known as 'The Divine One' for her rich, operatic voice.",
        "Mary Lou Williams was a mentor to Thelonious Monk, Charlie Parker, and Dizzy Gillespie.",
        "Grant Green was a Blue Note guitarist known for his single-note, horn-like lines.",
        "Joe Pass's 'Virtuoso' album set the standard for solo jazz guitar.",
        "Kenny Burrell was Duke Ellington's favorite guitarist.",
        "Freddie Hubbard played on pivotal albums like 'Free Jazz', 'The Blues and the Abstract Truth', and 'Ascension'.",
        "Wayne Shorter is regarded as one of jazz's greatest composers since Ellington.",
        "Lee Morgan was a trumpet prodigy who was tragically shot by his common-law wife at a gig.",
        "McCoy Tyner's modal chords essentially defined the sound of 60s jazz piano.",
        "Elvin Jones's polyrhythmic triplets fueled the intense energy of the Coltrane Quartet.",
        "Jazz originated in New Orleans in the late 19th and early 20th centuries.",
        "The word 'jazz' was originally a slang term for energy or vitality.",
        "Jelly Roll Morton claimed to have invented jazz in 1902.",
        "The Original Dixieland Jass Band recorded the first jazz record in 1917.",
        "Louis Armstrong's Hot Five and Hot Seven recordings are considered the foundation of jazz improvisation.",
        "Bix Beiderbecke was a cornetist who offered a cooler, more lyrical alternative to Armstrong's style.",
        "Coleman Hawkins is considered the father of the tenor saxophone in jazz.",
        "Ben Webster was known for his breathy, romantic tone on ballads.",
        "Roy Eldridge was a trumpet virtuoso who bridged the gap between Armstrong and Gillespie.",
        "Charlie Christian was a pioneer of the electric guitar and a key figure in the development of bebop.",
        "The birth of Cool Jazz is often associated with Miles Davis's 'Birth of the Cool' sessions.",
        "Hard Bop incorporated influences from blues, gospel, and R&B.",
        "Modal Jazz relies on musical modes rather than chord progressions as a harmonic framework.",
        "Free Jazz abandoned fixed chord progressions, tempos, and formal structures.",
        "Fusion blended jazz improvisation with rock rhythms and electric instruments.",
        "Smooth Jazz emerged in the 1970s as a commercially successful radio format.",
        "Latin Jazz combines jazz harmony with Latin American rhythms.",
        "Afro-Cuban Jazz was pioneered by Dizzy Gillespie and Chano Pozo.",
        "Third Stream attempts to blend jazz and classical music.",
        "Acid Jazz combines elements of jazz, soul, funk, and disco.",
        "Nu Jazz blends jazz with electronic music styles.",
        "The Jazz Age was a cultural period in the 1920s defined by the popularity of jazz music.",
        "Harlem Renaissance was a cultural movement that saw a flourishing of African American art and music.",
        "The Cotton Club was a famous Harlem nightclub where Duke Ellington and Cab Calloway performed.",
        "Tin Pan Alley was the center of the American music publishing industry in the early 20th century.",
        "The Great American Songbook is a canon of important popular songs from the early 20th century.",
        "Jazz standards are musical compositions that are widely known, performed, and recorded by jazz musicians.",
        "Improvisation is the act of composing music in the moment.",
        "Scat singing is vocal improvisation with wordless vocables.",
        "Call and response is a musical form where a leader sings or plays a phrase and a group responds.",
        "Polyrhythm is the simultaneous use of two or more conflicting rhythms.",
        "Syncopation involves stressing the weak beats or off-beats.",
        "Swing is a rhythmic feel where the eighth notes are played with a triplet feel.",
        "Blue notes are notes that are sung or played at a slightly lower pitch than the standard scale.",
        "The 12-bar blues is one of the most common chord progressions in popular music.",
        "A head arrangement is a musical arrangement that is memorized rather than written down.",
        "A jam session is an informal gathering of musicians to play improvised music.",
        "A sideman is a professional musician who is hired to perform or record with a group.",
        "A bandleader is the leader of a band of musicians.",
        "A big band is a type of musical ensemble that originated in the United States during the Swing Era.",
        "A combo is a small jazz group, typically consisting of 3 to 7 musicians.",
        "A rhythm section typically consists of piano, bass, drums, and sometimes guitar.",
        "A horn section typically consists of trumpets, trombones, and saxophones.",
        "The Newport Jazz Festival is one of the most famous jazz festivals in the world.",
        "The Montreux Jazz Festival is a famous music festival held annually in Switzerland.",
        "Blue Note Records is a famous jazz record label known for its hard bop releases.",
        "Verve Records is a famous jazz record label founded by Norman Granz.",
        "Impulse! Records is a famous jazz record label known for its avant-garde releases.",
        "ECM Records is a famous jazz record label known for its distinct aesthetic and sound.",
        "Jazz at Lincoln Center is a prominent jazz organization based in New York City."
    ],
    guitarHistory: [
        "The guitar's ancestors include the lute, oud, and vihuela.",
        "Antonio de Torres Jurado is considered the father of the modern classical guitar.",
        "Christian Frederick Martin invented the X-bracing system for steel-string guitars.",
        "Orville Gibson pioneered the archtop guitar, inspired by violin construction.",
        "Leo Fender introduced the first mass-produced solid-body electric guitar, the Broadcaster (later Telecaster).",
        "Les Paul was a pioneer of the solid-body electric guitar and multi-track recording.",
        "The Gibson Les Paul was introduced in 1952 as a collaboration between Gibson and Les Paul.",
        "The Fender Stratocaster, introduced in 1954, featured a contoured body and three pickups.",
        "The humbucking pickup was invented by Seth Lover at Gibson to reduce 60-cycle hum.",
        "The whammy bar (vibrato system) allows guitarists to alter the pitch of strings.",
        "Jimi Hendrix revolutionized electric guitar playing with his use of feedback and effects.",
        "Eric Clapton is known as 'Slowhand' and was a member of The Yardbirds, Cream, and Derek and the Dominos.",
        "Jimmy Page was a session musician before forming Led Zeppelin.",
        "Eddie Van Halen popularized the tapping technique on electric guitar.",
        "Stevie Ray Vaughan revived interest in blues guitar in the 1980s.",
        "B.B. King named his guitar 'Lucille' after saving it from a burning building.",
        "Chuck Berry is considered a pioneer of rock and roll guitar.",
        "Robert Johnson is a legendary blues guitarist who supposedly sold his soul to the devil.",
        "Muddy Waters was a key figure in the development of Chicago blues.",
        "T-Bone Walker was a pioneer of electric blues guitar.",
        "Charlie Christian was the first major electric jazz guitarist.",
        "Django Reinhardt created a unique style of jazz guitar known as Gypsy Jazz.",
        "Wes Montgomery played with his thumb to achieve a warm, mellow tone.",
        "Joe Pass was a virtuoso solo jazz guitarist known for his chord-melody playing.",
        "Pat Metheny is known for his use of guitar synthesizers and the 42-string Pikasso guitar.",
        "Allan Holdsworth was known for his advanced harmonic concepts and legato technique.",
        "John Scofield combines jazz with funk and R&B influences.",
        "Bill Frisell is known for his unique blend of jazz, country, and Americana.",
        "Julian Lage is a modern jazz guitar prodigy known for his technical mastery and musicality.",
        "Tommy Emmanuel is a master of the fingerstyle guitar technique.",
        "Chet Atkins was known as 'Mr. Guitar' and helped create the Nashville Sound.",
        "Merle Travis developed a fingerpicking style known as 'Travis picking'.",
        "Andrés Segovia is credited with establishing the guitar as a concert instrument.",
        "Francisco Tárrega is considered the father of modern classical guitar technique.",
        "Heitor Villa-Lobos wrote some of the most important works for classical guitar.",
        "The Rickenbacker 'Frying Pan' was the first electric lap steel guitar.",
        "The Bigsby vibrato tailpiece was the first successful vibrato system for electric guitars.",
        "The Floyd Rose locking tremolo system allows for extreme pitch changes without going out of tune.",
        "Active pickups use a battery-powered preamp to boost the signal and reduce noise.",
        "The synthesizer guitar allows guitarists to trigger synthesizer sounds.",
        "The 7-string guitar is often used in metal and jazz for extended range.",
        "The 12-string guitar produces a rich, chorus-like sound.",
        "The resonator guitar uses metal cones to amplify the sound.",
        "The pedal steel guitar is played with a metal bar and foot pedals.",
        "The ukulele is a small, four-stringed instrument of Portuguese origin popular in Hawaii.",
        "The banjo is a stringed instrument with a drum-like body.",
        "The mandolin is a small, eight-stringed instrument tuned in fifths.",
        "The sitar is a plucked string instrument used in Indian classical music.",
        "The koto is a traditional Japanese stringed instrument.",
        "The oud is a pear-shaped stringed instrument used in Middle Eastern music."
    ],
    guitarTechnique: [
        "Alternate picking involves strictly alternating down and up strokes.",
        "Economy picking combines alternate picking with sweep picking for efficiency.",
        "Sweep picking allows for playing arpeggios at high speeds.",
        "Legato technique involves using hammer-ons and pull-offs for a smooth sound.",
        "Tapping involves using the fingers of the picking hand to fret notes.",
        "Hybrid picking combines the use of a pick and fingers.",
        "Fingerstyle involves plucking the strings with the fingertips or fingernails.",
        "Travis picking is a syncopated fingerpicking style with an alternating bass line.",
        "Palm muting involves resting the palm on the strings to dampen the sound.",
        "String skipping involves jumping over strings to create wide intervals.",
        "Bending involves pushing or pulling a string to raise its pitch.",
        "Vibrato involves oscillating the pitch of a note for expression.",
        "Sliding involves moving a finger along a string to change pitch.",
        "Hammer-on involves striking a string with a fretting finger to sound a note.",
        "Pull-off involves plucking a string with a fretting finger to sound a lower note.",
        "Natural harmonics are bell-like tones produced by lightly touching the string at specific nodes.",
        "Artificial harmonics are produced by fretting a note and touching the string 12 frets higher.",
        "Pinch harmonics are produced by catching the string with the thumb of the picking hand.",
        "Tapping harmonics involves tapping the string at a harmonic node.",
        "Tremolo picking involves picking a single note rapidly and continuously.",
        "Rasgueado is a flamenco strumming technique using the fingers.",
        "Golpe is a percussive technique involving tapping the guitar body.",
        "Tambora is a percussive technique involving striking the strings near the bridge.",
        "Pizzicato involves muting the strings with the palm for a staccato sound.",
        "Campanella involves playing scale passages across different strings to let notes ring out.",
        "Rest stroke (apoyando) involves the finger coming to rest on the adjacent string after plucking.",
        "Free stroke (tirando) involves the finger clearing the adjacent string after plucking.",
        "Barre chords involve using one finger to fret multiple strings.",
        "Thumb over technique involves using the thumb to fret bass notes.",
        "Slide guitar involves using a glass or metal slide to change pitch.",
        "Open tunings allow for playing chords with a single finger or slide.",
        "Drop D tuning involves lowering the low E string to D.",
        "DADGAD is a popular alternate tuning for folk and Celtic music.",
        "Nashville tuning involves replacing the lower strings with higher octave strings.",
        "Capo allows for changing the key of the guitar without changing chord shapes.",
        "Metronome practice is essential for developing good time and rhythm.",
        "Slow practice helps to build muscle memory and accuracy.",
        "Visualization helps to reinforce mental maps of the fretboard.",
        "Ear training helps to connect the sounds in your head to the instrument.",
        "Transcription involves learning music by ear from recordings.",
        "Improvisation involves creating music spontaneously.",
        "Composition involves writing and arranging original music.",
        "Reading notation helps to access a wider range of musical literature.",
        "Music theory helps to understand the structure and function of music.",
        "Repertoire building involves learning and memorizing songs.",
        "Performance practice involves playing in front of an audience.",
        "Recording helps to critique and improve your playing.",
        "Jamming helps to develop communication and interaction skills.",
        "Listening to a wide variety of music helps to expand your musical vocabulary.",
        "Taking lessons from a qualified teacher can accelerate your progress."
    ],
    majorThirdsTuning: [
        "Major Thirds (M3) tuning tunes every string a major third apart (4 semitones).",
        "Standard tuning is E-A-D-G-B-E. M3 tuning is E-G#-C-E-G#-C (or similar).",
        "In M3 tuning, chord shapes and scale patterns are identical on every string set.",
        "M3 tuning eliminates the 'B-string bump' of standard tuning.",
        "M3 tuning makes learning the fretboard easier due to its symmetry.",
        "M3 tuning reduces the stretch required for some closed-position chords.",
        "M3 tuning allows for playing chromatic scales with 4 notes per string.",
        "M3 tuning is excellent for playing whole-tone scales and augmented chords.",
        "M3 tuning can limit the range of the guitar compared to standard tuning.",
        "M3 tuning often requires custom string gauges for balanced tension.",
        "Ralph Patt was a jazz guitarist who pioneered the use of M3 tuning.",
        "M3 tuning facilitates the visualization of interval relationships.",
        "In M3 tuning, a major triad is a straight line across three strings.",
        "In M3 tuning, an augmented triad is a straight line across three strings on the same fret.",
        "M3 tuning makes transposing ideas across strings effortless.",
        "M3 tuning is sometimes called 'regular tuning' because the interval between strings is constant.",
        "M3 tuning can be challenging for playing traditional open chords.",
        "M3 tuning is great for playing complex jazz voicings with tight intervals.",
        "M3 tuning allows for consistent fingering patterns for all scales and arpeggios.",
        "M3 tuning can be applied to 6, 7, or 8-string guitars.",
        "M3 tuning encourages a more interval-based approach to improvisation.",
        "M3 tuning simplifies the learning of inversions.",
        "M3 tuning makes it easier to play symmetrical patterns.",
        "M3 tuning can be a powerful tool for breaking out of standard tuning habits.",
        "M3 tuning requires relearning the fretboard if you are used to standard tuning.",
        "M3 tuning is used by some modern jazz and fusion players.",
        "M3 tuning can be adapted to different starting pitches (e.g., C-E-G#-C-E-G#).",
        "M3 tuning provides a fresh perspective on harmony and melody.",
        "M3 tuning allows for unique chord voicings not possible in standard tuning.",
        "M3 tuning is a logical system that aligns with the 12-tone equal temperament system.",
        "M3 tuning makes it easier to see the 'geometry' of music on the fretboard.",
        "M3 tuning can help to develop a more intuitive connection to the instrument.",
        "M3 tuning is a valid and effective alternative to standard tuning.",
        "M3 tuning can inspire new musical ideas and creativity.",
        "M3 tuning is worth exploring for any serious guitarist.",
        "M3 tuning reveals the isomorphic nature of the guitar fretboard.",
        "In M3 tuning, diagonal movement on the fretboard corresponds to specific intervals.",
        "M3 tuning simplifies the execution of large interval leaps.",
        "M3 tuning allows for easy modulation to any key.",
        "M3 tuning is particularly well-suited for atonal and 12-tone music.",
        "M3 tuning can be used to emulate the sound of other instruments like the piano.",
        "M3 tuning challenges the traditional role of the guitar.",
        "M3 tuning offers a unique pathway to musical mastery.",
        "M3 tuning is a testament to the versatility of the guitar.",
        "M3 tuning is a hidden gem in the world of guitar tunings.",
        "M3 tuning can unlock your potential as a musician.",
        "M3 tuning is a journey of discovery.",
        "M3 tuning is a beautiful and logical system.",
        "M3 tuning is the future of guitar? Maybe for some!",
        "M3 tuning: Try it, you might like it!"
    ],
    theory: [
        "Major 7th chords contain the interval of a major 7th - just one half step below the octave.",
        "The Mixolydian mode is a major scale with a flatted 7th - perfect for dominant 7th chords.",
        "Voice leading aims to move to the next chord with minimal motion - often just a half or whole step.",
        "Shell voicings use only the 3rd and 7th of a chord - the 'guide tones' that define its quality.",
        "The tritone (6 semitones) is the most unstable interval and creates the tension in dominant 7th chords.",
        "Drop 2 voicings are created by taking the second note from the top and dropping it an octave.",
        "The melodic minor scale is used over minor-major 7th chords and in altered dominant contexts.",
        "Relative major and minor keys share the same notes but start on different scale degrees.",
        "The circle of fifths shows all 12 keys and their relationships - essential for key changes.",
        "Chord extensions (9, 11, 13) add color without changing the fundamental chord quality.",
        "Secondary dominants are V7 chords of diantonic chords other than the tonic (e.g., V7/ii).",
        "A 'Turnaround' is a progression at the end of a section that leads back to the beginning (often I-vi-ii-V).",
        "Mode mixture (borrowed chords) involves using chords from the parallel minor key.",
        "The Lydian Dominant scale is the 4th mode of Melodic Minor and fits strictly over 7#11 chords.",
        "The Altered Scale (Super Locrian) is the 7th mode of Melodic Minor and fits over 7alt chords.",
        "Upper structure triads are triads played over a tritone shell to create complex tensions.",
        "Polychords consist of two chords played simultaneously (e.g., D major over C major).",
        "Quartal harmony builds chords in fourths rather than thirds, popularized by McCoy Tyner.",
        "So What voicings feature a stack of three perfect fourths and a major third on top.",
        "The Barry Harris method adds a 'sixth dimension' to bebop scales using the 6th diminished scale.",
        "Negative Harmony is a concept popularized by Jacob Collier involving inverting the tonal axis.",
        "A picardy third is ending a minor piece with a major chord.",
        "Backdoor dominance is a bVII7 resolving to Imaj7.",
        "Rhythm Changes is a 32-bar form based on 'I Got Rhythm' by George Gershwin.",
        "The Blues form is typically 12 bars with a I-IV-I-V-IV-I progression.",
        "Pentatonic scales have 5 notes and avoid the tritone, making them very consonant.",
        "Inside vs. Outside playing refers to playing diatonically vs. engaging with dissonance/chromaticism.",
        "Enclosure is a bebop technique of surrounding a target note with chromatic neighbors.",
        "Guide tones are usually the 3rd and 7th of a chord, determining its major/minor/dominant quality.",
        "Rootless voicings omit the root, assuming the bassist (or listener's ear) supplies it.",
        "The symmetric diminished scale is alternating whole and half steps (or half and whole).",
        "Whole tone scales have no semitones and sound dreamy or unsettled.",
        "Augmented chords are major triads with a raised 5th (#5).",
        "Diminished 7th chords are stacks of minor thirds and are symmetrical every 3 semitones.",
        "Slash chords indicate a specific bass note (e.g., C/G is C major with G in the bass).",
        "Pedal point is a sustained bass note while harmonies change above it.",
        "Line cliché is a chromatic movement within a static chord (e.g., m, mMaj7, m7, m6).",
        "Coltrane substitution involves moving tonal centers by major thirds.",
        "Targeting is aiming for a specific chord tone on a strong beat.",
        "Sideslipping is playing a motif a half-step away and resolving back.",
        "Sequence is repeating a melodic motif at different pitch levels.",
        "Tensions are non-chord tones (9, 11, 13) that are not 1, 3, 5, or 7.",
        "Avoid notes are scale tones that clash with a chord (e.g., natural 4 on a major chord).",
        "Syncopation stresses the weak beats or off-beats.",
        "Hemiola is a rhythmic feel of 3 against 2.",
        "Swing feel involves delaying the second eighth note of a pair.",
        "Polyrythm is the simultaneous use of two or more conflicting rhythms.",
        "Rubato is expressively speeding up and slowing down the tempo.",
        "Vamp is a repeating musical figure or chord progression.",
        "Head is the main melody of a jazz tune, usually played at the start and end."
    ],
    practice: [
        "Slow practice builds more accurate muscle memory than fast, sloppy repetition.",
        "Try singing the chord tones as you play them - it connects your ear to your fingers.",
        "Practicing in all 12 keys might seem tedious, but it builds real musical fluency.",
        "The best musicians practice with intention - quality over quantity.",
        "Recording yourself is one of the fastest ways to identify areas for improvement.",
        "When learning voicings, start with shells, then add extensions gradually.",
        "Major thirds tuning reduces stretch - the same voicing shapes work across the fretboard.",
        "Transposing songs to different keys is excellent ear training.",
        "Use a metronome, but also practice playing 'ahead' or 'behind' the beat intentionally.",
        "Limit your options: Try soloing using only 3 notes or only on one string.",
        "Learn melodies by ear, not just from tab/sheet music, to strengthen your listening.",
        "Practice transitions between chords, not just the chords themselves.",
        "Isolate the difficult 2 measures and loop them until they flow.",
        "Visualization: Imagine playing the instrument perfectly without touching it.",
        "Rest is part of learning. Your brain consolidates skills while you sleep.",
        "Transcribe solos: Write down what you hear to understand the player's vocabulary.",
        "Don't just practice scales up and down; use intervals and patterns.",
        "Play with backing tracks, but also play solo to ensure your time feel is solid.",
        "Learn the lyrics to jazz standards to understand the phrasing of the melody.",
        "Practice dynamics: Can you play the same phrase whisper quiet and roaring loud?",
        "Record a loop and practice comping (accompaniment) for yourself.",
        "Work on your tone. A simple line played with great tone beats a complex sloppy one.",
        "Challenge yourself to learn one new tune per week.",
        "Analyze a song's harmonic structure (Roman numerals) to memorize it faster.",
        "Practice 'call and response' with recordings.",
        "Focus on rhythm first. The 'wrong' note in the right rhythm sounds better than the right note in wrong rhythm.",
        "Take breaks. 20 minutes of focused work is better than 2 hours of distracted noodling.",
        "Keep a practice journal to track your progress and goals.",
        "Learn the root motion of a progression first, then add 3rds and 7ths.",
        "Practice common cadences (ii-V-I) in all keys as a warm-up.",
        "Use the Circle of Fifths to organize your practice routine.",
        "Noodle creatively at the end of a session as a reward, but keep the core session structured.",
        "If you make a mistake, repeat the phrase correctly 3 times to overwrite the error.",
        "Practice 'stopping' - leaving space in your solos.",
        "Listen to music actively. What is the bass doing? What is the drummer doing?",
        "Sing your solo ideas before you play them.",
        "Learn comping rhythms from listening to pianists and drummers, not just guitarists.",
        "Explore different picks and fingerstyle techniques to vary your timbre.",
        "Ensure your posture is relaxed to prevent injury and tension.",
        "Tune your hearing: Can you identify intervals (major 3rd, perfect 5th) by ear?",
        "Don't rely solely on visual shapes; know the note names you are playing.",
        "Mix up your routine. Do technique one day, repertoire the next.",
        "Teach what you learn. Explaining a concept helps you understand it better.",
        "Practice ending phrases on chord tones.",
        "Emulate horn players to develop better phrasing and breath in your lines.",
        "Learn the 'head' (melody) in multiple octaves.",
        "Improvising is composing in real-time. Make your lines melodic.",
        "Don't fear mistakes. In jazz, a 'wrong' note is just a halftone away from a 'right' one.",
        "Consistency is key. 15 minutes every day is better than 4 hours once a week.",
        "Enjoy the process. You are building a lifelong relationship with music."
    ],
};

export class PracticePartner {
    private static userName: string | null = null;
    private static style: 'concise' | 'balanced' | 'supportive' = 'balanced';
    private static lastFactTime: number = 0;
    private static factCooldownMs: number = 120000; // 2 minutes between facts

    static getGreeting(lastSessionDate: Date | null, lastSessionQuality: 'excellent' | 'challenging' | 'exploratory'): string {
        if (!lastSessionDate) {
            return "Ready to explore some harmony?";
        }

        const daysSince = Math.floor((Date.now() - lastSessionDate.getTime()) / (1000 * 60 * 60 * 24));

        if (daysSince > 7) {
            return "Welcome back! Been a while. Want to review what you were working on?";
        } else if (lastSessionQuality === 'excellent') {
            return "Ready to keep that momentum going?";
        } else if (lastSessionQuality === 'challenging') {
            return "Want to tackle that progression again, or try something new?";
        } else {
            return "What shall we work on today?";
        }
    }

    static getEncouragement(state: EmotionalState, achievement?: string): string | null {
        switch (state) {
            case 'frustrated':
                return "This progression is tricky. Want to try a simpler version first?";
            case 'bored':
                return "You've mastered this! Ready for something new?";
            case 'breakthrough':
                return "Your voice leading just leveled up 📈";
            case 'engaged':
                if (achievement === 'smoothVoiceLeading') return "That voice leading was smooth 🎵";
                if (achievement === 'quickRecognition') return "Nice! You found that quickly";
                return null;
            default:
                return null;
        }
    }

    /**
     * Get a random educational fact - respects cooldown to avoid being annoying
     * Returns null if called too frequently
     */
    static getRandomFact(): { category: string; fact: string } | null {
        const now = Date.now();

        // Respect cooldown period
        if (now - this.lastFactTime < this.factCooldownMs) {
            return null;
        }

        // 30% chance to show a fact even when cooldown has passed
        if (Math.random() > 0.3) {
            return null;
        }

        this.lastFactTime = now;

        const categories = Object.keys(MUSIC_FACTS) as (keyof typeof MUSIC_FACTS)[];
        const category = categories[Math.floor(Math.random() * categories.length)];
        const facts = MUSIC_FACTS[category];
        const fact = facts[Math.floor(Math.random() * facts.length)];

        const categoryLabels: Record<string, string> = {
            bossaNova: '🇧🇷 Bossa Nova',
            jazz: '🎷 Jazz History',
            theory: '🎵 Music Theory',
            practice: '💡 Practice Tip',
            guitarHistory: '🎸 Guitar History',
            guitarTechnique: '👐 Guitar Technique',
            majorThirdsTuning: '🔧 Major Thirds Tuning',
        };

        return {
            category: categoryLabels[category] || category,
            fact,
        };
    }

    /**
     * Force get a fact (ignores cooldown) - for initial page loads
     */
    static getInitialFact(): { category: string; fact: string } {
        const categories = Object.keys(MUSIC_FACTS) as (keyof typeof MUSIC_FACTS)[];
        const category = categories[Math.floor(Math.random() * categories.length)];
        const facts = MUSIC_FACTS[category];
        const fact = facts[Math.floor(Math.random() * facts.length)];

        const categoryLabels: Record<string, string> = {
            bossaNova: '🇧🇷 Bossa Nova',
            jazz: '🎷 Jazz History',
            theory: '🎵 Music Theory',
            practice: '💡 Practice Tip',
        };

        this.lastFactTime = Date.now();

        return {
            category: categoryLabels[category] || category,
            fact,
        };
    }
}
